function SendOrder(Instrument, Direction, Offsetflag, Volume, Price)
%ÏÂµ¥
global td;
td.SendOrder(Instrument, ...
                        Direction, ...
                        Offsetflag, ...
                        '1', ...
                        Volume, ...
                        Price, ...
                        QuantBox.CSharp2CTP.TThostFtdcOrderPriceTypeType.LimitPrice,...
                        QuantBox.CSharp2CTP.TThostFtdcTimeConditionType.GFD,...
                        QuantBox.CSharp2CTP.TThostFtdcContingentConditionType.Immediately,...
                        0, ...
                        QuantBox.CSharp2CTP.TThostFtdcVolumeConditionType.AV);

end

