function SendOrder(Instrument, Direction, Offsetflag, Volume, Price)
%下单
global td hCTPGUI;
if(isempty(td))
    if(isempty(hCTPGUI))
        warning('未连接交易端');
    else
        set(hCTPGUI.FailText, 'String', '未连接交易端');
    end
    
    
else
    td.SendOrder(Instrument, ...
                        Direction, ...
                        Offsetflag, ...
                        '1', ...
                        Volume, ...
                        Price, ...
                        QuantBox.CSharp2CTP.TThostFtdcOrderPriceTypeType.LimitPrice,...
                        QuantBox.CSharp2CTP.TThostFtdcTimeConditionType.GFD,...
                        QuantBox.CSharp2CTP.TThostFtdcContingentConditionType.Immediately,...
                        0, ...
                        QuantBox.CSharp2CTP.TThostFtdcVolumeConditionType.AV);
end


end

